/**
 * LLM-as-judge helpers for compliance report quality evaluation.
 *
 * Uses Claude to score compliance reports on domain-specific dimensions:
 * regulatory accuracy, finding specificity, remediation quality, evidence rigor.
 */

// @ts-expect-error — optional dependency, only used in LLM judge evals
import Anthropic from "@anthropic-ai/sdk";

const client = new Anthropic();

export interface ComplianceJudgeScore {
	regulatory_accuracy: number; // 1-5: correct HIPAA § references
	finding_specificity: number; // 1-5: specific file/line vs vague
	remediation_quality: number; // 1-5: actionable fix steps
	evidence_rigor: number; // 1-5: hashed evidence, chain of custody
	reasoning: string;
}

export interface ComplianceOutcomeResult {
	detected: string[];
	missed: string[];
	false_positives: number;
	detection_rate: number;
	evidence_quality: number; // 1-5
	reasoning: string;
}

/**
 * Generic LLM judge: send a prompt to Claude and extract JSON from the response.
 * Retries on 429 rate limits.
 */
export async function callJudge<T>(prompt: string, maxRetries = 3): Promise<T> {
	for (let attempt = 0; attempt < maxRetries; attempt++) {
		try {
			const response = await client.messages.create({
				model: "claude-sonnet-4-6",
				max_tokens: 1024,
				messages: [{ role: "user", content: prompt }],
			});

			const text = response.content
				.filter((b: { type: string }) => b.type === "text")
				.map((b: { type: string; text: string }) => b.text)
				.join("");

			// Extract JSON from response (may be wrapped in markdown code blocks)
			const jsonMatch =
				text.match(/```json?\s*([\s\S]*?)```/) || text.match(/(\{[\s\S]*\})/);
			if (!jsonMatch) throw new Error("No JSON found in judge response");
			return JSON.parse(jsonMatch[1]) as T;
		} catch (err: unknown) {
			if (
				err instanceof Error &&
				(err as unknown as Record<string, unknown>).status === 429 &&
				attempt < maxRetries - 1
			) {
				await new Promise((r) => setTimeout(r, 2000 * (attempt + 1)));
				continue;
			}
			throw err;
		}
	}
	throw new Error("Judge retries exhausted");
}

/**
 * Score a compliance report on quality dimensions.
 */
export async function judgeComplianceReport(
	skillName: string,
	reportContent: string,
): Promise<ComplianceJudgeScore> {
	const prompt = `You are evaluating the quality of a HIPAA compliance report generated by the "${skillName}" skill.

Report content:
---
${reportContent.slice(0, 8000)}
---

Score this report on 4 dimensions (1-5 scale each):

1. **regulatory_accuracy**: Are HIPAA section references (e.g., §164.312(a)(1)) correct and relevant? 5 = all references accurate, 1 = missing or incorrect references.

2. **finding_specificity**: Are findings tied to specific files, lines, or resources? 5 = every finding has file:line or resource ARN, 1 = vague "you should check encryption."

3. **remediation_quality**: Are remediation steps actionable and complete? 5 = copy-pasteable fixes with before/after, 1 = generic advice like "enable encryption."

4. **evidence_rigor**: Does the report reference collected evidence, hashes, or audit trails? 5 = SHA-256 manifests, timestamped evidence dirs, 1 = no evidence mentioned.

Respond with ONLY a JSON object:
\`\`\`json
{
  "regulatory_accuracy": <1-5>,
  "finding_specificity": <1-5>,
  "remediation_quality": <1-5>,
  "evidence_rigor": <1-5>,
  "reasoning": "<brief explanation>"
}
\`\`\``;

	return callJudge<ComplianceJudgeScore>(prompt);
}

/**
 * Score outcome of a planted-violation detection test.
 */
export async function judgeComplianceOutcome(
	reportContent: string,
	groundTruth: { bugs: Array<{ id: string; description: string }> },
): Promise<ComplianceOutcomeResult> {
	const bugList = groundTruth.bugs
		.map((b) => `- ${b.id}: ${b.description}`)
		.join("\n");

	const prompt = `You are evaluating whether a HIPAA compliance scanner correctly detected planted violations.

Known planted violations:
${bugList}

Scanner output:
---
${reportContent.slice(0, 8000)}
---

Determine which violations were detected and which were missed.
A violation counts as "detected" if the report mentions the specific issue (even if phrased differently).

Respond with ONLY a JSON object:
\`\`\`json
{
  "detected": ["<bug-id>", ...],
  "missed": ["<bug-id>", ...],
  "false_positives": <number of findings that don't match any planted violation>,
  "detection_rate": <number of bugs detected>,
  "evidence_quality": <1-5, how well does the report document evidence for each finding>,
  "reasoning": "<brief explanation>"
}
\`\`\``;

	return callJudge<ComplianceOutcomeResult>(prompt);
}
